"""
ActionSource Enum — Phase 8.

Indicates whether an action plan was generated by the AI model or
the deterministic fallback service.
"""
from enum import Enum


class ActionSource(str, Enum):
    GEMINI   = "GEMINI"
    FALLBACK = "FALLBACK"
