"""
Constants and thresholds for the deterministic Analyzer Node.
"""

# Health Classification Thresholds
CPU_NORMAL_MAX = 50.0
CPU_HEALTHY_MAX = 70.0
CPU_WARNING_MAX = 80.0
CPU_HIGH_MAX = 90.0

# Restart Rule
RESTART_THRESHOLD = 3

# Replica Rule
CPU_REPLICA_THRESHOLD = 85.0
REPLICA_MIN_COUNT = 1

# Spike / Sustained CPU Rules
SPIKE_CURRENT_MIN = 90.0
SPIKE_AVG_MAX = 50.0
SUSTAINED_CURRENT_MIN = 90.0
SUSTAINED_5M_MIN = 85.0
SUSTAINED_15M_MIN = 80.0

# Node Contention Rule
NODE_CPU_CONTENTION_THRESHOLD = 95.0
NODE_CONTENTION_POD_LIMIT_PERCENTAGE = 80.0

# Confidence Scoring Rules
CONFIDENCE_MAX = 100
CONFIDENCE_CPU_OVER_90 = 30
CONFIDENCE_5M_OVER_85 = 20
CONFIDENCE_15M_OVER_80 = 20
CONFIDENCE_RESTARTS_OVER_3 = 15
CONFIDENCE_HISTORY_EXISTS = 15

# General
THROTTLING_LIMIT_THRESHOLD = 90.0
